version: '3'
services:

  rabbit.mq.test:
    container_name: rabbit.mq.test
    image: rabbitmq:3.12.0-management-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"